Repository DIT112-V20/group-03, pull requests merged in 2020-05, with the labels that each got.

#67 [Web Application] - carController and joystick changes
  Server/online.quar/pom.xml
  Server/online.quar/src/main/java/online/quar/application/Constants.java
  Server/online.quar/src/main/java/online/quar/application/MvcConfig.java
  Server/online.quar/src/main/java/online/quar/application/manager/AuthenticationManager.java
  Server/online.quar/src/main/java/online/quar/application/manager/CarManager.java
  Server/online.quar/src/main/java/online/quar/application/manager/UserManager.java
  Server/online.quar/src/main/resources/static/dist/app.js
  Server/online.quar/src/main/resources/static/dist/jquery-3.5.0.min.js
  Server/online.quar/src/main/resources/static/dist/nipplejs.js
  Server/online.quar/src/main/resources/static/dist/scale.fix.js
  Server/online.quar/src/main/resources/static/script/joystick.js
  Server/online.quar/src/main/resources/static/styles/carController.css
  Server/online.quar/src/main/resources/static/styles/carStyles.css
  Server/online.quar/src/main/resources/static/styles/github-light.css
  Server/online.quar/src/main/resources/static/styles/hello.css
  Server/online.quar/src/main/resources/static/styles/home.css
  Server/online.quar/src/main/resources/static/styles/login.css
  Server/online.quar/src/main/resources/templates/pages/carController.html
  Server/online.quar/src/test/java/online/quar/application/JunitTestSuite.java
  Server/online.quar/src/test/java/online/quar/application/TestRunner.java
  Server/online.quar/src/test/java/online/quar/application/model/CarTest.java
  Server/online.quar/src/test/java/online/quar/application/model/TestCar.java
Labels: Sprint#3

#68 [WebApplication] - Create foundation for API, including REST and WebSocket templates and tests
  Server/online.quar/pom.xml
  Server/online.quar/src/main/java/online/quar/application/config/MvcConfig.java
  Server/online.quar/src/main/java/online/quar/application/config/ServerConfig.java
  Server/online.quar/src/main/java/online/quar/application/config/WebSecurityConfig.java
  Server/online.quar/src/main/java/online/quar/application/config/WebSocketConfig.java
  Server/online.quar/src/main/java/online/quar/application/controller/Controller.java
  Server/online.quar/src/main/java/online/quar/application/controller/GreetingController.java
  Server/online.quar/src/main/java/online/quar/application/manager/RouteManager.java
  Server/online.quar/src/main/java/online/quar/application/model/Greeting.java
  Server/online.quar/src/main/java/online/quar/application/model/HelloMessage.java
  Server/online.quar/src/main/java/online/quar/application/model/Route.java
  Server/online.quar/src/main/resources/static/script/app.js
  Server/online.quar/src/main/resources/templates/pages/webSocketOrgTest.html
  Server/online.quar/src/main/resources/templates/pages/webSocketTest.html
  Server/online.quar/src/test/java/online/quar/application/JunitTestSuite.java
  Server/online.quar/src/test/java/online/quar/application/controller/HelloControllerIT.java
  Server/online.quar/src/test/java/online/quar/application/controller/TestController.java
Labels: Sprint#4

#69 [Car] - refactoring of car classes
  Car/TeamNull SmartCar/src/main.cpp
  Car/TeamNull SmartCar/src/main.hpp
  Car/TeamNull SmartCar/src/manager/MovementManager.cpp
  Car/TeamNull SmartCar/src/manager/MovementManager.hpp
  Car/TeamNull SmartCar/src/manager/WifiManager.cpp
  Car/TeamNull SmartCar/src/manager/WifiManager.hpp
  Car/TeamNull SmartCar/src/util/HardwareUtil.cpp
Labels: Sprint#4

#70 [WebApplication] - Feed user input from the WebApp to the server.
  Car/TeamNull SmartCar/src/manager/MovementManager.cpp
  Car/TeamNull SmartCar/src/util/HardwareUtil.cpp
  Car/TeamNull SmartCar/src/util/HardwareUtil.hpp
  Server/online.quar/src/main/java/online/quar/application/QuarOnlineApplication.java
  Server/online.quar/src/main/java/online/quar/application/config/WebSocketConfig.java
  Server/online.quar/src/main/java/online/quar/application/controller/WSController.java
  Server/online.quar/src/main/java/online/quar/application/manager/ApplicationManager.java
  Server/online.quar/src/main/java/online/quar/application/manager/CarManager.java
  Server/online.quar/src/main/java/online/quar/application/manager/DatabaseManager.java
  Server/online.quar/src/main/java/online/quar/application/manager/UserManager.java
  Server/online.quar/src/main/java/online/quar/application/model/Car.java
  Server/online.quar/src/main/java/online/quar/application/model/CarControlInput.java
  Server/online.quar/src/main/resources/sql/sql_getCar.sql
  Server/online.quar/src/main/resources/sql/sql_getUser.sql
  Server/online.quar/src/main/resources/static/script/carControlApp.js
  Server/online.quar/src/main/resources/static/script/stompDemoApp.js
  Server/online.quar/src/main/resources/templates/pages/carController.html
  Server/online.quar/src/main/resources/templates/pages/webSocketTest.html
Labels: Sprint#4

#74 [Entire stack] - Build API in Web Application, and connect car
  Car/TeamNull SmartCar/src/main.cpp
  Car/TeamNull SmartCar/src/manager/MovementManager.cpp
  Car/TeamNull SmartCar/src/manager/MovementManager.hpp
  Car/TeamNull SmartCar/src/manager/WifiManager.cpp
  Car/TeamNull SmartCar/src/util/Base64.cpp
  Car/TeamNull SmartCar/src/util/Base64.h
  Car/TeamNull SmartCar/src/util/HardwareUtil.cpp
  Car/TeamNull SmartCar/src/util/WebSocketClient.cpp
  Car/TeamNull SmartCar/src/util/WebSocketClient.h
  Car/TeamNull SmartCar/src/util/global.h
  Car/TeamNull SmartCar/src/util/sha1.cpp
  Car/TeamNull SmartCar/src/util/sha1.h
  Car/TeamNull SmartCar/src_obstacle_avoidance/main.cpp
  Server/online.quar/src/main/java/Main.java
  Server/online.quar/src/main/java/online/quar/application/ApplicationSecurity.java
  Server/online.quar/src/main/java/online/quar/application/config/WebSecurityConfig.java
  Server/online.quar/src/main/java/online/quar/application/controller/Controller.java
  Server/online.quar/src/main/java/online/quar/application/controller/RestfulController.java
  Server/online.quar/src/main/java/online/quar/application/controller/WSController.java
  Server/online.quar/src/main/java/online/quar/application/model/CarControlInput.java
  Server/online.quar/src/main/resources/application.properties
  Server/online.quar/src/main/resources/static/dist/app.js
  Server/online.quar/src/main/resources/static/script/carControlApp.js
  Server/online.quar/src/main/resources/templates/pages/carController.html
  Server/online.quar/src/test/java/online/quar/application/JunitTestSuite.java
  Server/online.quar/src/test/java/online/quar/application/controller/TestRestfulController.java
Labels: Sprint#4

#78 [Web Application] - minor css changes
  Server/online.quar/src/main/resources/static/styles/hello.css
  Server/online.quar/src/main/resources/static/styles/home.css
  Server/online.quar/src/main/resources/static/styles/login.css
Labels: Sprint#5

#81 [CI Implementation] - Run unit tests
  .travis.yml
  Car/TeamNull CarCam/src/main.cpp
  Car/TeamNull SmartCar/src/main.cpp
  Car/TeamNull SmartCar/src/manager/MovementManager.cpp
  Car/TeamNull SmartCar/src/manager/MovementManager.hpp
  Car/TeamNull SmartCar/src/manager/WifiManager.cpp
  Car/TeamNull SmartCar/src/manager/WifiManager.hpp
  Car/TeamNull SmartCar/src/util/HardwareUtil.cpp
  Car/TeamNull SmartCar/src/util/HardwareUtil.hpp
  README.md
  Server/online.quar/pom.xml
  Server/online.quar/src/main/java/online/quar/application/config/WebSecurityConfig.java
  Server/online.quar/src/main/java/online/quar/application/controller/RestfulController.java
  Server/online.quar/src/main/resources/static/dist/nipplejs.js
  Server/online.quar/src/main/resources/static/script/carControlApp.js
  Server/online.quar/src/main/resources/templates/pages/carController.html
  Server/online.quar/src/test/java/online/quar/application/JunitTestSuite.java
  Server/online.quar/src/test/java/online/quar/application/TestRunner.java
  Server/online.quar/src/test/java/online/quar/application/model/TestCar.java
Labels: Sprint#5

#86 [WebApplication] - UI enhancements
  Car/TeamNull SmartCar/.idea/.gitignore
  Car/TeamNull SmartCar/src/main.cpp
  Car/TeamNull SmartCar/src/manager/MovementManager.cpp
  Car/TeamNull SmartCar/src/manager/MovementManager.hpp
  Car/TeamNull SmartCar/src/manager/WifiManager.cpp
  Car/TeamNull SmartCar/src/util/HardwareUtil.cpp
  Server/online.quar/src/main/java/online/quar/application/QuarOnlineApplication.java
  Server/online.quar/src/main/java/online/quar/application/config/MvcConfig.java
  Server/online.quar/src/main/java/online/quar/application/config/ServerConfig.java
  Server/online.quar/src/main/java/online/quar/application/config/WebSecurityConfig.java
  Server/online.quar/src/main/java/online/quar/application/config/WebSocketConfig.java
  Server/online.quar/src/main/java/online/quar/application/controller/RestfulController.java
  Server/online.quar/src/main/java/online/quar/application/controller/WSController.java
  Server/online.quar/src/main/java/online/quar/application/manager/AuthenticationManager.java
  Server/online.quar/src/main/java/online/quar/application/manager/CarManager.java
  Server/online.quar/src/main/java/online/quar/application/manager/DatabaseManager.java
  Server/online.quar/src/main/java/online/quar/application/manager/UserManager.java
  Server/online.quar/src/main/java/online/quar/application/model/Car.java
  Server/online.quar/src/main/java/online/quar/application/model/CarControlInput.java
  Server/online.quar/src/main/java/online/quar/application/model/Greeting.java
  Server/online.quar/src/main/java/online/quar/application/model/HelloMessage.java
  Server/online.quar/src/main/java/online/quar/application/model/Route.java
  Server/online.quar/src/main/java/online/quar/application/util/Logger.java
  Server/online.quar/src/main/resources/application.properties
  Server/online.quar/src/main/resources/sql/sql_getUserById.sql
  Server/online.quar/src/main/resources/sql/sql_getUserByUserName.sql
  Server/online.quar/src/main/resources/static/script/carControlApp.js
  Server/online.quar/src/main/resources/static/script/stompDemoApp.js
  Server/online.quar/src/main/resources/static/styles/carController.css
  Server/online.quar/src/main/resources/static/styles/general.css
  Server/online.quar/src/main/resources/templates/pages/carController.html
  Server/online.quar/src/main/resources/templates/pages/login.html
  Server/online.quar/src/main/resources/templates/pages/webSocketOrgTest.html
  Server/online.quar/src/main/resources/templates/pages/webSocketTest.html
Labels: Sprint#6

#92 [Car] - Obstacle avoidance #59
  Car/TeamNull SmartCar/src/main.cpp
  Car/TeamNull SmartCar/src/manager/MovementManager.cpp
  Car/TeamNull SmartCar/src/manager/MovementManager.hpp
  Car/TeamNull SmartCar/src/manager/WifiManager.cpp
  Car/TeamNull SmartCar/src/manager/WifiManager.hpp
  Car/TeamNull SmartCar/src/util/HardwareUtil.cpp
  Car/TeamNull SmartCar/src/util/HardwareUtil.hpp
  README.md
  Server/online.quar/src/main/java/online/quar/application/controller/WSController.java
  Server/online.quar/src/main/java/online/quar/application/manager/CarManager.java
  Server/online.quar/src/main/java/online/quar/application/manager/RouteManager.java
  Server/online.quar/src/main/java/online/quar/application/model/Car.java
  Server/online.quar/src/main/java/online/quar/application/model/CarControlInput.java
  Server/online.quar/src/main/java/online/quar/application/model/Route.java
  Server/online.quar/src/main/resources/static/script/carControlApp.js
  Server/online.quar/src/main/resources/templates/pages/carController.html
  Server/online.quar/src/main/resources/templates/pages/home.html
Labels: Sprint#7

#93 [WebApplication] - Change input from linear to logarithmic
  Server/online.quar/src/main/java/online/quar/application/manager/RouteManager.java
  Server/online.quar/src/main/java/online/quar/application/model/Route.java
Labels: Sprint#7

#94 [WebApplication] - Bugfixing
  Server/online.quar/src/main/java/online/quar/application/manager/RouteManager.java
Labels: Sprint#7

#95 [README] - Finalise readme
  README.md
  Server/online.quar/src/main/java/online/quar/application/config/WebSecurityConfig.java
Labels: Sprint#7
